"""
Auto Docs - Project-Level Documentation Generators
Handles multi-file documentation, README generation, API references, and usage examples
"""

from typing import Dict, Any, Optional, List
from pathlib import Path
from lib.utils import get_timestamp


async def generate_project_docs(
    auto_docs,
    project_path: str,
    output_dir: str = "docs",
    file_patterns: Optional[List[str]] = None
) -> Dict[str, Any]:
    """Generate documentation for an entire project."""
    if file_patterns is None:
        file_patterns = ['*.py', '*.js', '*.ts', '*.java']

    project_root = Path(project_path)
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    results = {
        "success": True,
        "files_processed": 0,
        "files_failed": 0,
        "output_directory": str(output_path),
        "files": []
    }

    files_to_document = []
    for pattern in file_patterns:
        files_to_document.extend(project_root.rglob(pattern))

    for file_path in files_to_document:
        try:
            docs = await auto_docs.generate_docs(str(file_path), "full")

            relative_path = file_path.relative_to(project_root)
            output_file = output_path / f"{relative_path}.md"
            output_file.parent.mkdir(parents=True, exist_ok=True)

            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(docs)

            results["files_processed"] += 1
            results["files"].append({
                "source": str(file_path),
                "output": str(output_file),
                "status": "success"
            })

        except Exception as e:
            results["files_failed"] += 1
            results["files"].append({
                "source": str(file_path),
                "status": "failed",
                "error": str(e)
            })

    return results


def generate_api_reference(code: str, language: str, ai_content: str = "") -> str:
    """
    Generate API reference documentation.
    
    Args:
        code: Source code as a string (must not be None)
        language: Programming language of the code
        ai_content: AI-generated content to include
        
    Returns:
        API reference documentation as a string
    """
    if ai_content:
        return ai_content
    
    api_ref = [
        "# API Reference\n",
        f"**Language:** {language}\n",
        "\n## Overview\n",
        "\nThis section provides API documentation for the code.\n",
        "\n## Functions and Methods\n",
        "\n(Generated by watsonx.ai)\n"
    ]
    return "".join(api_ref)


def generate_usage_examples(code: str, language: str, ai_content: str = "") -> str:
    """
    Generate usage examples for code.
    
    Args:
        code: Source code as a string (must not be None)
        language: Programming language of the code
        ai_content: AI-generated content to include
        
    Returns:
        Usage examples as a string
    """
    if ai_content:
        return ai_content
        
    examples = [
        "# Usage Examples\n",
        f"\n**Language:** {language}\n",
        "\n## Basic Usage\n",
        "\n```" + language.lower() + "\n",
        "// Example usage will be generated here\n",
        "```\n"
    ]
    return "".join(examples)


def generate_user_manual(code: str, language: str, ai_content: str = "") -> str:
    """
    Generate comprehensive user manual.
    
    Args:
        code: Source code as a string
        language: Programming language
        ai_content: AI-generated content
        
    Returns:
        User manual documentation
    """
    if ai_content:
        return f"""# User Manual

**Language:** {language}

{ai_content}

---
*Generated by AutoDocs - User Manual Generator*
"""
    return "# User Manual\n\n(Content will be generated by AI)"


def generate_how_to_guide(code: str, language: str, ai_content: str = "") -> str:
    """
    Generate step-by-step how-to guide.
    
    Args:
        code: Source code as a string
        language: Programming language
        ai_content: AI-generated content
        
    Returns:
        How-to guide documentation
    """
    if ai_content:
        return f"""# How-To Guide

**Language:** {language}

{ai_content}

---
*Generated by AutoDocs - How-To Guide Generator*
"""
    return "# How-To Guide\n\n(Content will be generated by AI)"


def generate_quick_start_guide(code: str, language: str, ai_content: str = "") -> str:
    """
    Generate quick-start guide.
    
    Args:
        code: Source code as a string
        language: Programming language
        ai_content: AI-generated content
        
    Returns:
        Quick-start guide documentation
    """
    if ai_content:
        return f"""# Quick Start Guide

**Language:** {language}

{ai_content}

---
*Generated by AutoDocs - Quick Start Generator*
"""
    return "# Quick Start Guide\n\n(Content will be generated by AI)"


def generate_tutorial(code: str, language: str, ai_content: str = "") -> str:
    """
    Generate interactive tutorial.
    
    Args:
        code: Source code as a string
        language: Programming language
        ai_content: AI-generated content
        
    Returns:
        Tutorial documentation
    """
    if ai_content:
        return f"""# Tutorial

**Language:** {language}

{ai_content}

---
*Generated by AutoDocs - Tutorial Generator*
"""
    return "# Tutorial\n\n(Content will be generated by AI)"


def generate_troubleshooting_guide(code: str, language: str, ai_content: str = "") -> str:
    """
    Generate troubleshooting guide.
    
    Args:
        code: Source code as a string
        language: Programming language
        ai_content: AI-generated content
        
    Returns:
        Troubleshooting guide documentation
    """
    if ai_content:
        return f"""# Troubleshooting Guide

**Language:** {language}

{ai_content}

---
*Generated by AutoDocs - Troubleshooting Generator*
"""
    return "# Troubleshooting Guide\n\n(Content will be generated by AI)"


def generate_user_persona(code: str, language: str, ai_content: str = "") -> str:
    """
    Generate user personas.
    
    Args:
        code: Source code as a string
        language: Programming language
        ai_content: AI-generated content
        
    Returns:
        User persona documentation
    """
    if ai_content:
        return f"""# User Personas

**Language:** {language}

{ai_content}

---
*Generated by AutoDocs - User Persona Generator*
"""
    return "# User Personas\n\n(Content will be generated by AI)"


def generate_knowledge_base_article(code: str, language: str, ai_content: str = "") -> str:
    """
    Generate knowledge base article.
    
    Args:
        code: Source code as a string
        language: Programming language
        ai_content: AI-generated content
        
    Returns:
        Knowledge base article
    """
    if ai_content:
        return f"""# Knowledge Base Article

**Language:** {language}

{ai_content}

---
*Generated by AutoDocs - Knowledge Base Generator*
"""
    return "# Knowledge Base Article\n\n(Content will be generated by AI)"


def generate_ux_design_doc(code: str, language: str, ai_content: str = "") -> str:
    """
    Generate UX design documentation.
    
    Args:
        code: Source code as a string
        language: Programming language
        ai_content: AI-generated content
        
    Returns:
        UX design documentation
    """
    if ai_content:
        return f"""# UX Design Documentation

**Language:** {language}

{ai_content}

---
*Generated by AutoDocs - UX Design Generator*
"""
    return "# UX Design Documentation\n\n(Content will be generated by AI)"


def generate_wireframe(code: str, language: str, ai_content: str = "") -> str:
    """
    Generate wireframe documentation.
    
    Args:
        code: Source code as a string
        language: Programming language
        ai_content: AI-generated content
        
    Returns:
        Wireframe documentation with ASCII art or descriptions
    """
    if ai_content:
        return f"""# Wireframe Documentation

**Language:** {language}

{ai_content}

---
*Generated by AutoDocs - Wireframe Generator*
"""
    return "# Wireframe Documentation\n\n(Content will be generated by AI)"


def generate_software_requirements(code: str, language: str, ai_content: str = "") -> str:
    """
    Generate software requirements specification.
    
    Args:
        code: Source code as a string
        language: Programming language
        ai_content: AI-generated content
        
    Returns:
        Software requirements specification
    """
    if ai_content:
        return f"""# Software Requirements Specification

**Language:** {language}

{ai_content}

---
*Generated by AutoDocs - Requirements Generator*
"""
    return "# Software Requirements Specification\n\n(Content will be generated by AI)"


async def generate_readme(
    project_path: str,
    project_name: Optional[str] = None
) -> str:
    """Generate a README.md for a project."""
    if project_name is None:
        project_name = Path(project_path).name

    project_root = Path(project_path)
    files = list(project_root.rglob("*"))

    readme = [
        f"# {project_name}\n",
        f"\n**Generated:** {get_timestamp()}\n",
        "\n## Overview\n",
        "\nThis project contains the following structure:\n",
        "\n## Project Structure\n",
        "\n```",
        f"\n{project_name}/",
    ]

    for file in sorted(files)[:20]:
        if file.is_file():
            relative = file.relative_to(project_root)
            readme.append(f"\n--- {relative}")

    readme.append("\n```\n")
    readme.append("\n## Installation\n")
    readme.append("\n(Installation instructions will be added here)\n")
    readme.append("\n## Usage\n")
    readme.append("\n(Usage instructions will be added here)\n")
    readme.append("\n## License\n")
    readme.append("\n(License information will be added here)\n")

    return "".join(readme)

# Made with Bob
