"""
Doc Engine - Project-Level Documentation Generators
Handles multi-file documentation, README generation, API references, and usage examples
"""

from typing import Dict, Any, Optional, List
from pathlib import Path
from lib.utils import get_timestamp


async def generate_project_docs(
    doc_engine,
    project_path: str,
    output_dir: str = "docs",
    file_patterns: Optional[List[str]] = None
) -> Dict[str, Any]:
    """Generate documentation for an entire project."""
    if file_patterns is None:
        file_patterns = ['*.py', '*.js', '*.ts', '*.java']

    project_root = Path(project_path)
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    results = {
        "success": True,
        "files_processed": 0,
        "files_failed": 0,
        "output_directory": str(output_path),
        "files": []
    }

    files_to_document = []
    for pattern in file_patterns:
        files_to_document.extend(project_root.rglob(pattern))

    for file_path in files_to_document:
        try:
            docs = await doc_engine.generate_docs(str(file_path), "full")

            relative_path = file_path.relative_to(project_root)
            output_file = output_path / f"{relative_path}.md"
            output_file.parent.mkdir(parents=True, exist_ok=True)

            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(docs)

            results["files_processed"] += 1
            results["files"].append({
                "source": str(file_path),
                "output": str(output_file),
                "status": "success"
            })

        except Exception as e:
            results["files_failed"] += 1
            results["files"].append({
                "source": str(file_path),
                "status": "failed",
                "error": str(e)
            })

    return results


def generate_api_reference(code: str, language: str) -> str:
    """Generate API reference documentation (static template)."""
    api_ref = [
        "# API Reference\n",
        f"**Language:** {language}\n",
        "\n## Overview\n",
        "\nThis section provides API documentation for the code.\n",
        "\n## Functions and Methods\n",
        "\n(Generated by watsonx.ai)\n"
    ]
    return "".join(api_ref)


def generate_usage_examples(code: str, language: str) -> str:
    """Generate usage examples for code (static template)."""
    examples = [
        "# Usage Examples\n",
        f"\n**Language:** {language}\n",
        "\n## Basic Usage\n",
        "\n```" + language.lower() + "\n",
        "// Example usage will be generated here\n",
        "```\n"
    ]
    return "".join(examples)


async def generate_readme(
    project_path: str,
    project_name: Optional[str] = None
) -> str:
    """Generate a README.md for a project."""
    if project_name is None:
        project_name = Path(project_path).name

    project_root = Path(project_path)
    files = list(project_root.rglob("*"))

    readme = [
        f"# {project_name}\n",
        f"\n**Generated:** {get_timestamp()}\n",
        "\n## Overview\n",
        "\nThis project contains the following structure:\n",
        "\n## Project Structure\n",
        "\n```",
        f"\n{project_name}/",
    ]

    for file in sorted(files)[:20]:
        if file.is_file():
            relative = file.relative_to(project_root)
            readme.append(f"\n--- {relative}")

    readme.append("\n```\n")
    readme.append("\n## Installation\n")
    readme.append("\n(Installation instructions will be added here)\n")
    readme.append("\n## Usage\n")
    readme.append("\n(Usage instructions will be added here)\n")
    readme.append("\n## License\n")
    readme.append("\n(License information will be added here)\n")

    return "".join(readme)
